### ISSUE TITLE
it doesn't work when  switching tabs

### ISSUE THREAD

**Issue by TonyLuo** [djett41/ionic-scroll-sista#1]

**Comment by djett41** [comment]
@TonyLuo do you have the scroll-sista directive on the ion-content for each tab you want scroll behavior?  Check out the latest demo, I just added more chat items so you can see how it works.

putting the scroll-sista directive on the ion-content and switching between tabs seems to work fine.

**Comment by TonyLuo** [comment]
@djett41 I only put the scroll-sista directive on one tab because I want  one tab shrink the header only.
Is it a must to put the  scroll-sista directive on each tab?

**Comment by djett41** [comment]
Yes @TonyLuo as of the current version, you will need to put it on any ion-content that needs it (kind of the same way ionic requires has-subheader class for each content that has a subheader)

**Comment by djett41** [comment]
@TonyLuo is this still an issue when switching tabs?

**Comment by TonyLuo** [comment]
@djett41 it works well. the version i am using is 1.0.2.
