### ISSUE TITLE
<ion-nav-bar> unhides when scroller reaches to the bottom of the page with a flicker.

### ISSUE THREAD

**Issue by desmochai** [djett41/ionic-scroll-sista#23]
Consider this markup:
<img width="895" alt="screen shot 2015-10-05 at 6 33 55 pm" src="https://cloud.githubusercontent.com/assets/2950322/10278410/b9e0179e-6b8f-11e5-81a2-0f2574652964.png">
<img width="1100" alt="screen shot 2015-10-05 at 6 34 13 pm" src="https://cloud.githubusercontent.com/assets/2950322/10278409/b9df84a0-6b8f-11e5-9b7e-2327e7f0e78c.png">

I would really appreciate your suggestions. Thank you :)

**Comment by desmochai** [comment]
I commented out the below if condition, it works like a charm :+1: 

if (scrollView.getScrollMax().top - scrollTop <= contentTop) {
       y = 0;
        duration = defaultDuration;
 }

In my opinion, it would be awesome if this was configurable.

**Comment by djett41** [comment]
Thanks! I'm linking this to another current issue with the same request!

**Comment by desmochai** [comment]
Also, if you have spare time and review @flavordaaave pull request. I really want the snap option in my app. Thank you
