### ISSUE TITLE
Scroll Sista stopped working

### ISSUE THREAD

**Issue by druearmstrong** [djett41/ionic-scroll-sista#3]
First, thank you for the work on scroll-sista. I have been wanting to implement a shrinking header, actually sub header and was hacking up the code pen shrinking header bar when I ran across your work.

I am not sure why the scroll sister stopped working for me. It worked. Now it doesn't. Is there a bower or node version/issue I am unaware of?

node version: v0.12.7
bower version: 1.4.1

**Comment by druearmstrong** [comment]
I was re-reading the details and I did change the js include from bower/~ to lib/~ 

Not sure if the js file has to live under bower or not. Have not had a chance to test this yet either.

**Comment by druearmstrong** [comment]
After much research and builds, here are my findings:
ionic serve - works!
ionic serve --lab - does not work
Xcode build - does not work on device

**Comment by Shinzah** [comment]
Hi, and thank for scroll-sista initiative !
I have the same issue.
Sometime it works, and sometime not...
I use directive on multiple views, in the same way, and on the first it work, and others not ...
Maybe a conflict when the directive is used in multiple views ?

**Comment by djett41** [comment]
Thanks guys!  What version of ionic UI are you on? If you have a codepen I can look at I can take a look!  It seems to work everytime in the demo app I put together so I'm wondering if its conflicting with something in your template?  Let me know and I'll try to find a fix thanks!

**Comment by druearmstrong** [comment]
Thanks for looking into this. Scroll Sista is a great solution and I hope to get this resolved.

Here is the .bower.jason file:
"name": "ionic",
"version": "1.0.0-rc.5",

**Comment by Shinzah** [comment]
Hi, i can give you an access to my ionic app webversion.
Could you contact me at shin@sw-db.fr, i'll give you login/pwd for the dev version ?

**Comment by druearmstrong** [comment]
Hi -

Do we have any updates to this issue? 
Have you been able to get the directive to work on a device?
Still waiting for a solution to this issue.

**Comment by darthdie** [comment]
I was able to get it to work by wrapping the code in "link" with a $timeout. It appears it's having trouble getting the scrolldelegate/view. I'm wondering if it isn't a problem with collection-repeat loading later than the directive? Not sure, haven't had a chance to dig further.

**Comment by druearmstrong** [comment]
Thanks for looking into the issue. That would make sense for the sporadic working/not working results I'm getting. What is "link" that you wrapped the directive in?

**Comment by darthdie** [comment]
Ah, sorry! Inside the main scroll sista library/dist/ionic.scroll.sista.js at line 14 is the "link" directive function. So you just then wrap everything in that with a $timeout. Again I can't promise that this will fix it 100% but in my tests it's worked.

**Comment by druearmstrong** [comment]
@darthdie 

Thanks for the detailed follow up. I will try this and let you know how this works out.
Did your tests include devices? Thanks again.

**Comment by druearmstrong** [comment]
@darthdie -

perhaps I am missing something - wrapping the $timeout seems to break the script.
Am I not wrapping the $timeout correctly?

return {
    restrict: 'A',
    $timeout(function () {
         link: function($scope, $element, $attr) {
         ....
- then after the switch statement
  }, 3000, false);

**Comment by darthdie** [comment]
You'd do it like this:
https://github.com/darthdie/ionic-scroll-sista/blob/master/dist/ionic.scroll.sista.js

The issue with this method is that there will naturally be a delay before it begins working. The only reliable way I've found for it to work without the delay is to add a scroll-delegate to your ion-content element.

**Comment by druearmstrong** [comment]
Thanks for clarifying how to wrap the directive in the $timeout method.
Well, script is not broken now but I still can't seem to get it to work. 

Here's my test screen with a list

<ion-view view-title="Genres" class='genres view'>

```
<ion-header-bar class="bar-subheader content-wrapper flex-container">
    <div class="vod-mark">
        <img src="img/vod-logo-white.png" alt="logo"/>
    </div>

    <div class="row tabs-striped">
        <div class="col tab-item">
            <a href="#/app/discover" menu-close>Discover</a>
            <div class="col icon"></div>
        </div>

        <div class="col tab-item active">
            Genres
            <div class="col icon ion-arrow-down-b"></div>
        </div>

        <div class="col tab-item">
            <a href="#/app/intelligentmix" menu-close>Intelligent Mix</a>
            <div class="col icon"></div>
        </div>
    </div> 
</ion-header-bar>

<ion-content scroll-sista class="layout has-subheader" padding='false'>

    <!-- <ion-refresher pulling-icon="ion-load-b" on-refresh="refreshItems()">
    </ion-refresher> -->

    <ion-list>
        <ion-item back-img="{{playlist.image}}" bindonce ng-repeat="playlist in playlists" href="#/app/genres/{{playlist.id}}" >
            <!-- <div class="title-fill"></div> -->
            <div class="genre-title">
               {{playlist.title}}
                <i class="icon ion-ios-arrow-right"></i>
            </div>

        </ion-item>
    </ion-list>
</ion-content>
```

</ion-view>

**Comment by djett41** [comment]
from another issue here...

 I have been looking at this and am trying to find a way to consistently grab the active navbar.  The navbar changes to different statuses (active/leaving/staging/cached/entering) not in that exact order, but for some reason it's not grabbing the correct navbar and the cached and active are getting switched.  I believe this is the root of most of the issues that are being seen here

**Comment by druearmstrong** [comment]
While I appreciate the reference, our app will be deployed in 185 countries and all 50 states here. Obviously with such a high end client I can't put a band aid on this issue. 

Even with wrapping the timeout within the method, I still don't see a consistent experience.
I have til the end of next month to resolve this issue and would really like to feature your work in the app.
Is there anything else you see that might be causing the issue?

**Comment by djett41** [comment]
I'm going to ask the ionic team if they can add an event we can listen to when the nav bar is finished animating/switching.  Because trying to get the active/cached navbar right now is pretty inconsistent.  There may be some other hacky ways to accomplish this, but it would be great if we had a sure way of knowing when they navbar is done switching out statuses

**Comment by druearmstrong** [comment]
That sounds like a solid idea. Really appreciate the willingness for getting behind your directive and working with us for a stable solution.

**Comment by djett41** [comment]
@druearmstrong @darthdie @Shinzah  This should be fixed now.  Just released 1.0.3, and am figured out a way to get the headers correctly

**Comment by Shinzah** [comment]
Hi, 
Thank for your work, it work like a charm !

**Comment by djett41** [comment]
Great to hear!! I am closing this issue.

**Comment by Hesesses** [comment]
For me it works on browser, but not on a device.. I'm using 1.0.6 version. Any ideas?

**Comment by Hesesses** [comment]
Anyone? Is it working for you? For me it works on browsers but not on devices
