### ISSUE TITLE
Allow scroll-sista="header-subheader"

### ISSUE THREAD

**Issue by meneliksteiner** [djett41/ionic-scroll-sista#7]
First, thank you for this awesome plugin ;)
Is there any way to combine header and subheader together? I would like to hide only the header+subheader but still keep the tabs visible. Is there a option planed like scroll-sista="header-subheader"?

**Comment by djett41** [comment]
Thanks! there is now!! Oops forgot to link the issue, but I added both "subheader-header" which for top tabs slides subheader first then header, or "header-subheader" which for top tabs will slide out header first then subheader.  Thanks!  Not sure why I didnt think about that @siam2nite

**Comment by meneliksteiner** [comment]
thank you for implementing this so fast! Really appreciate it ;)

**Comment by djett41** [comment]
no prob!! Thanks for contributiing
