### ISSUE TITLE
Multiple tab sets

### ISSUE THREAD

**Issue by locrianmode** [djett41/ionic-scroll-sista#9]
I have an application that has a side menu with multiple tab sets, each set displayed when clicking on a menu item. 

I found that the scroll-sista directive always refers to the first tab which work. Clicking to display subsequent tab sets will not work. 

This is due to the following (line 86 in ionic.scroll.sista.js) , which will always refer to the first tab set.
`tabs = body.querySelector('.tabs');`

Changing to the following works
`tabs = body.querySelectorAll('.tabs')[body.querySelectorAll('.tabs').length - 1];`

**Comment by djett41** [comment]
Thanks @locrianmode !!! Works! Just released new verison
